POST http://localhost:3001/api/items
Content-Type: application/json

{
    "title": "testing from the backend",
    "content": "hi",
    "due": "01/01/2026",
    "importance": 1,
    "label": "TEST LABEL"
}